AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template creates a static website with a public and private subnet on an EC2
Parameters:
  KeyPair:
    Description: select your keypair
    Type: AWS::EC2::KeyPair::KeyName
    Default: test_002
  EC2-Type:
    Description: select your instance type
    Type: string
    Default: t2.micro
    AllowedValues:
         - t2.micro
         - t3.micro

  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64'       
Resources:
  SG-StaWeb:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow 22 and 80 ports # Required      
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp          
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: HTTP         
          ToPort: 80
      
  
  

  
Outputs: